<?php


namespace App\Admin\Actions;


class BatchAction extends \Encore\Admin\Actions\BatchAction
{

    protected function rename(){
        return $this->name;
    }
    public function render()
    {
        $this->name = $this->rename();
        return parent::render(); // TODO: Change the autogenerated stub
    }
    public function actionScript()
    {
        $warning = __('未选择数据!');

        return <<<SCRIPT
        var key = $.admin.grid.selected();
        
        if (key.length === 0) {
            $.admin.toastr.warning('{$warning}', '', {positionClass: 'toast-top-center'});
            return ;
        }
        
        Object.assign(data, {_key:key});
SCRIPT;
    }
}